language: c++
sudo: false

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew upgrade cmake || brew install cmake
    fi

script:
 - mkdir -p "${TRAVIS_BUILD_DIR}/build"
 - cd "${TRAVIS_BUILD_DIR}/build"
 - cmake -DCMAKE_BUILD_TYPE=Release "${TRAVIS_BUILD_DIR}"
 - make
 - ./test/test_cpuid
 - ./test/test_ref
 - ./test/test_sse2
 - ./test/test_ssse3
 - ./test/test_sse41
 - ./test/test_sde

matrix:
  include: 
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 CXX=g++-6"

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL=""

before_install:
  - eval "${MATRIX_EVAL}"
